/*
Symbols in the agn symbol fonts
*/

/* avoiding using 0 */
#define AGN_SYM_BELL    1
#define AGN_SYM_MEMO    2
#define AGN_SYM_CHEVRON 3  /* could use CHAR 175 of standard fonts instead */
#define AGN_SYM_CANDLE  4
#define AGN_SYM_UNTIL_ARROW 5  
#define AGN_SYM_BULLET      6
#define AGN_SYM_NONBRK_SPACE  7
#define AGN_SYM_TODO_PTY(X) (11+X)
#define AGN_SYM_UP_ARROW      24
#define AGN_SYM_DOWN_ARROW    25
#define AGN_SYM_RIGHT_ARROW   26
#define AGN_SYM_LEFT_ARROW    27
