#define  P_FCHG_UNKNOWN        0
#define  P_FCHG_NOTCHARGING    1
#define  P_FCHG_FASTCHARGING   2
#define  P_FCHG_TOPPINGOFF     3
#define  P_FCHG_TRICKLE        4

#define  P_FCHG_DEFAULTCC      0x0000
#define  P_FCHG_CC100mA        0x1000
#define  P_FCHG_CC200mA        0x2000
#define  P_FCHG_CC350mA        0x3000
#define  P_FCHG_CC500mA        0x4000
#define  P_FCHG_CC650mA        0x5000
#define  P_FCHG_CC800mA        0x8000
#define  P_FCHG_CC1000mA       0xa000
#define  P_FCHG_CC1200mA       0xc000
#define  P_FCHG_CC1400mA       0xe000

#define  P_FCHG_CTIME1C        2
#define  P_FCHG_CTIME2C        6
#define  P_FCHG_CTIMEC2        4
#define  P_FCHG_CTIMEC4        0

#define  P_FCHG_SETCHARGEMODE  0
#define  P_FCHG_READCHARGEMODE 1
#define  P_FCHG_READSTATUS     2
#define  P_FCHG_CLOSE          3
#define  P_FCHG_CANCEL         4
#define  P_FCHG_FASTCHARGE1    5
#define  P_FCHG_FASTCHARGE2    6
#define  P_FCHG_DISCHARGE      7
#define  P_FCHG_ASYNCHREAD     8
#define  P_FCHG_RESETBOTH      9
