/*	HEADER - P_NMSYS.H
Copyright (C) Psion PLC 1991-92
 VER    DATE   BY  DESCRIPTION
===== ======== === ===========
1.00F 26/04/90 NSM First relase
1.10F 07/07/92 NSM Second release
*/
#define P_NMSYS_H
#include <stdepoc.h>
#define P_SYSNAME_FIL 0
#define P_SYSNAME_TIM 1
#define P_SYSNAME_TTY 2
#define P_SYSNAME_HMD 3
#define P_SYSNAME_MAS 4
#define P_SYSNAME_LLC 5
#define P_SYSNAME_NLC 6
#define P_SYSNAME_XMD 7
#define P_SYSNAME_NCP 8
