/*
PAGESIZE.H
*/
#define PAGE_WIDTH_A4           11906  /* 210mm */
#define PAGE_LENGTH_A4          16838  /* 297mm */
#define PAGE_WIDTH_LEGAL        12240  /* 8.5in */
#define PAGE_LENGTH_LEGAL       20160  /* 14in */
#define PAGE_WIDTH_EXECUTIVE    10440  /* 7.25in */
#define PAGE_LENGTH_EXECUTIVE   15120  /* 10.5in */
#define PAGE_WIDTH_LETTER       12240  /* 8.5in */
#define PAGE_LENGTH_LETTER      15840  /* 11in */
#define PAGE_WIDTH_COM_10       5940   /* 4.125in */
#define PAGE_LENGTH_COM_10      13680  /* 9.5in */
#define PAGE_WIDTH_MONARCH      5580   /* 3.825in */
#define PAGE_LENGTH_MONARCH     10800  /* 7.5in */
#define PAGE_WIDTH_DL           6236   /* 110mm */
#define PAGE_LENGTH_DL          12472  /* 220mm */
#define PAGE_WIDTH_C5           9184   /* 162mm */
#define PAGE_LENGTH_C5          12983  /* 229mm */

