/*	HEADER - PLIB.H
Copyright (C) Psion PLC 1991-92
 VER    DATE   BY  DESCRIPTION
===== ======== === ===========
1.00F 26/04/90 NSM First relase
1.10F 07/07/92 NSM Second release
*/
#define PLIB_H
#include <stdepoc.h>
#include <p_std.h>
#include <epoc.h>
#include <p_object.h>
#include <p_date.h>
#include <p_file.h>
#include <p_gen.h>
#include <p_math.h>
#include <p_prdrv.h>
#include <p_graf.h>
#include <p_sys.h>
