; Names and widths of the pictures in the symbols font

WS_SYMBOL_SHOW_CR         equ	0
WS_WIDTH_SHOW_CR          equ	6

WS_SYMBOL_ELLIPSIS        equ	1
WS_WIDTH_ELLIPSIS         equ	6

WS_SYMBOL_PSION           equ	2
WS_WIDTH_PSION            equ	5

WS_SYMBOL_POWERX          equ	3
WS_WIDTH_POWERX           equ	5

WS_SYMBOL_NOTE_ICON       equ	4
WS_WIDTH_NOTE_ICON        equ	6

WS_SYMBOL_PHONE           equ	5
WS_WIDTH_PHONE            equ	6

WS_SYMBOL_PADLOCK         equ	6 
WS_WIDTH_PADLOCK          equ	6

WS_SYMBOL_HARD_HYPHEN     equ	7
WS_WIDTH_HARD_HYPHEN      equ	6

WS_SYMBOL_SHOW_SPACE      equ	8
WS_WIDTH_SHOW_SPACE       equ	3

WS_SYMBOL_SHOW_TAB        equ	9
WS_WIDTH_SHOW_TAB         equ	6

WS_SYMBOL_LINE_BREAK      equ	10
WS_WIDTH_LINE_BREAK       equ	6

WS_SYMBOL_SQROOT          equ	11
WS_WIDTH_SQROOT           equ	6

WS_SYMBOL_TICK		  equ	12
WS_WIDTH_TICK		  equ	8

WS_SYMBOL_DOWN_ARROWHEAD  equ	13
WS_WIDTH_DOWN_ARROWHEAD   equ	7

WS_SYMBOL_SOFT_HYPHEN     equ	14
WS_WIDTH_SOFT_HYPHEN      equ	6

WS_SYMBOL_HARD_SPACE      equ	15
WS_WIDTH_HARD_SPACE       equ	3

WS_SYMBOL_RIGHT_ARROWHEAD equ	16
WS_WIDTH_RIGHT_ARROWHEAD  equ	5

WS_SYMBOL_LEFT_ARROWHEAD  equ	17
WS_WIDTH_LEFT_ARROWHEAD   equ	5

WS_SYMBOL_WHITE_BOX1      equ	18
WS_WIDTH_WHITE_BOX1       equ	6

WS_SYMBOL_WHITE_BOX2      equ	19
WS_WIDTH_WHITE_BOX2       equ	5

WS_SYMBOL_GREY_BOX1       equ	20
WS_WIDTH_GREY_BOX1        equ	6

WS_SYMBOL_GREY_BOX2       equ	21
WS_WIDTH_GREY_BOX2        equ	5

WS_SYMBOL_BLACK_BOX1      equ	22
WS_WIDTH_BLACK_BOX1       equ	6

WS_SYMBOL_BLACK_BOX2      equ	23
WS_WIDTH_BLACK_BOX2       equ	5

WS_SYMBOL_UP_KEY          equ	24
WS_WIDTH_UP_KEY           equ	6

WS_SYMBOL_DOWN_KEY        equ	25
WS_WIDTH_DOWN_KEY         equ	6

WS_SYMBOL_RIGHT_KEY       equ	26
WS_WIDTH_RIGHT_KEY        equ	8

WS_SYMBOL_LEFT_KEY        equ	27
WS_WIDTH_LEFT_KEY         equ	8

WS_SYMBOL_MARGIN_CURSOR   equ	28
WS_WIDTH_MARGIN_CURSOR    equ	5

WS_SYMBOL_BELL            equ	29
WS_WIDTH_BELL             equ	6 

WS_SYMBOL_UP_ARROWHEAD    equ	30
WS_WIDTH_UP_ARROWHEAD     equ	7

WS_SYMBOL_NS		  equ	31
WS_WIDTH_NS		  equ	6

WS_SYMBOL_POWER2          equ	253
WS_WIDTH_POWER2           equ	4

WS_SYMBOL_BULLET          equ	254
WS_WIDTH_BULLET           equ	5

; Positioning of special characters in the special array

H_SC_TPLUS      equ	0       ; T is for Tag */
H_SC_TMINUS     equ	1
H_SC_TSTAR      equ	2
H_SC_TSLASH     equ	3

H_SC_ILESS      equ	4       ; I is for Incrementer
H_SC_ICOMMA     equ	5
H_SC_IMORE      equ	6
H_SC_IDOT       equ	7

H_SC_HFANCY     equ	8       ; H is for Hyphen

H_SC_LLN        equ 9       ; The following are North, South, West, East
H_SC_LLS        equ 10
H_SC_LLW        equ 11
H_SC_LLE        equ 12
H_SC_DEGREE     equ 13      ; As used in LatLong editor
H_SC_BULLET     equ 14      ; As used in help list
